apiVersion: v1
kind: Service
metadata:
  name: reimbursement-frontend
  namespace: reimbursement
spec:
  type: NodePort
  selector:
    app: reimbursement-frontend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
